### ISSUE TITLE
typo on https://rdap.rcode3.com/misc/finding_ip_networks.html

### ISSUE THREAD

**Issue by hadmut** [anewton1998/rdap_guide#12]
The page 

https://rdap.rcode3.com/misc/finding_ip_networks.html

begins with an example 

echo "start address", "end address", "cidr block" > ip_inventory.csv
cat ip_inventory.txt | while read ip
...

where the echo command should probably write into ip_inventory.txt and not .csv, because that way the cat doesn't work, and the .csv should be result and not input of the example

**Comment by hadmut** [comment]
Sorry, invalid, misunderstood.

**Comment by hadmut** [comment]
Wasn't obvious that the ip addresses above go into ip_inventory.txt

**Comment by anewton1998** [comment]
That's for looking at this. If you find other issues or see where it could be improved, please let me know. Thanks.
